spring.application.name=iam-server

server.port=9000

spring.datasource.url=jdbc:mysql://localhost:3306/iam_db
spring.datasource.username=root
spring.datasource.password=vijayan@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2.server.authorization=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000